services:
  frontend:
    build: docker/nuxt
    volumes:
      - type: bind
        source: ./frontend
        target: /src
      - type: volume
        target: /src/node_modules
    tty: true
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      - CHOKIDAR_USEPOLLING=true
