services:
  frontend:
    build: frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /src
    tty: true
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      - CHOKIDAR_USEPOLLING=true
